// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// AlertDialogClass: instance of this type is always passed by reference.
type AlertDialogClass struct {
	*alertDialogClass
}

// alertDialogClass is the struct that's finalized.
type alertDialogClass struct {
	native *C.AdwAlertDialogClass
}

func (a *AlertDialogClass) ParentClass() *DialogClass {
	valptr := &a.native.parent_class
	var _v *DialogClass // out
	_v = (*DialogClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
