// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// PreferencesDialogClass: instance of this type is always passed by reference.
type PreferencesDialogClass struct {
	*preferencesDialogClass
}

// preferencesDialogClass is the struct that's finalized.
type preferencesDialogClass struct {
	native *C.AdwPreferencesDialogClass
}

// ParentClass: parent class.
func (p *PreferencesDialogClass) ParentClass() *DialogClass {
	valptr := &p.native.parent_class
	var _v *DialogClass // out
	_v = (*DialogClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
